Repository Weather-Vortex/weather-vortex-server, pull requests merged in 2021-08, with the labels that each got.

#14 Openweathermap call
  .env.examples
  .github/workflows/test.yml
  README.md
  package-lock.json
  package.json
  src/index.js
  src/routes/forecasts.routes.js
  src/storages/location.storage.js
  src/storages/openweathermap.storage.js
  src/storages/storage.utils.js
  src/storages/troposhpere.storage.js
  src/storages/weatherProvider.js
  test/forecasts.test.js
  test/storages/storage.utils.test.js
  test/storages/weatherProvider.test.js
Labels: enhancement

#16 Env vars
  .env.examples
  .github/workflows/test.yml
  package-lock.json
  package.json
  src/config/config.js
  src/index.js
  src/models/user.model.js
  src/storages/location.storage.js
  src/storages/openweathermap.storage.js
  src/storages/troposhpere.storage.js
  test/forecasts.test.js
Labels: enhancement

#20 Confermation email corretto
  package-lock.json
  package.json
  src/config/config.js
  src/config/nodemailer.config.js
  src/index.js
  src/models/user.model.js
  src/routes/auth.routes.js
  src/services/auth.service.js
  src/storages/auth.storage.js
  test/auth.test.js
Labels: duplicate

#32 Cors enabling
  .env.examples
  README.md
  package-lock.json
  package.json
  src/config/cors.config.js
  src/index.js
Labels: bug, documentation

#40 Copy bug fixes from iot-weather.
  .github/workflows/deploy.yml
Labels: bug
